name       : python-pathspec
version    : 0.8.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pathspec/pathspec-0.8.1.tar.gz : 86379d6b86d75816baba717e64b1a3a3469deb93bb76d613c9ce79edc5cb68fd
homepage   : https://github.com/cpburnz/python-path-specification
license    : MPL-2.0
component  : programming.python
summary    : Utility library for gitignore style pattern matching of file paths
description: |
    pathspec is a utility library for pattern matching of file paths. So far this only includes Git's wildmatch pattern matching which itself is derived from Rsync's wildmatch. Git uses wildmatch for its gitignore files.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
