name       : python-pathspec
version    : 0.9.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/pathspec/pathspec-0.9.0.tar.gz : e564499435a2673d586f6b2130bb5b95f04a3ba06f81b8f895b651a3c76aabb1
homepage   : https://github.com/cpburnz/python-path-specification
license    : MPL-2.0
component  : programming.python
summary    : Utility library for gitignore style pattern matching of file paths
description: |
    pathspec is a utility library for pattern matching of file paths. So far this only includes Git's wildmatch pattern matching which itself is derived from Rsync's wildmatch. Git uses wildmatch for its gitignore files.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
