name       : python-pathspec
version    : 0.10.1
release    : 5
source     :
    - https://github.com/cpburnz/python-pathspec/archive/refs/tags/v0.10.1.tar.gz : 92dac078a8644d61b59bf0735986399a0694f470093069bf48ee66fa3553a095
homepage   : https://github.com/cpburnz/python-path-specification
license    : MPL-2.0
component  : programming.python
summary    : Utility library for gitignore style pattern matching of file paths
description: |
    pathspec is a utility library for pattern matching of file paths. So far this only includes Git's wildmatch pattern matching which itself is derived from Rsync's wildmatch. Git uses wildmatch for its gitignore files.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
